### PR TITLE
option to use AWS DynamoDB for integrations tests + fix empty table bug

### LINKED ISSUE #24: Feature: add the option to manually run the integration tests against a real DynamoDB instance on AWS
### Feature description

the current integration tests only run against the dynamodb docker instance, add the option to manually test against real AWS DyanmoDB

### PR DESCRIPTION
**Pull request by maha-mstfa**
### Description

Fixes #24 

### Quick checks:

- [ ] There is no other [pull request](https://github.com/conduitio-labs/conduit-connector-dynamodb/pulls) for the same update/change.
- [ ] I have written unit tests.
- [ ] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

File: source_integration_test.go [hunk 1]
```diff
@@ -153,6 +155,21 @@ func TestSource_EmptyTable(t *testing.T) {
...
 
+	// test CDC after an empty snapshot.
+	err = insertRecord(ctx, client, testTable, 0, 1)
+	is.NoErr(err)
+
+	for {
+		rec, err := source.Read(ctx)
+		if errors.Is(err, sdk.ErrBackoffRetry) {
+			continue
+		}
```
Comment (hariso) [inline source_integration_test.go:171]: If there's a bug in the source, we could get into an infinite loop here. So I believe it would be good to add a timeout to the ctx and run source.Read() in a goroutine.

**Review by hariso — APPROVED** [review]
LGTM!
